apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../runner
patches:
  - target:
      kind: Job
      name: qoodish-runner
    patch: |-
      - op: replace
        path: /metadata/name
        value: qoodish-destroy-unattached-images
      - op: add
        path: /spec/template/spec/template/spec/containers/0/args
        value:
          - bin/rails
          - images:destroy_unattached
