steps:
- name: gcr.io/cloud-builders/gcloud
  args:
    - kms
    - decrypt
    - --ciphertext-file=firebase-credentials.prod.json.enc
    - --plaintext-file=firebase-credentials.json
    - --location=global
    - --keyring=qoodish
    - --key=qoodish
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-api:$COMMIT_SHA',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-api:latest',
    '.'
  ]
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-api:latest'
