steps:
  - name: gcr.io/kaniko-project/executor
    args:
      - --cache=true
      - --cache-ttl=6h
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME-api:$COMMIT_SHA
      - --destination
      - gcr.io/$PROJECT_ID/$REPO_NAME-api:latest
