steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud kms decrypt --ciphertext-file=firebase-credentials.prod.json.enc --plaintext-file=firebase-credentials.json --location=global --keyring=qoodish --key=qoodish
      gcloud kms decrypt --ciphertext-file=gcp-credentials.prod.json.enc --plaintext-file=gcp-credentials.json --location=global --keyring=qoodish --key=qoodish
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/$REPO_NAME-api:$REVISION_ID', '.']
images: ['gcr.io/$PROJECT_ID/$REPO_NAME-api:$REVISION_ID']
