steps:
  - id: secret-manager
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        gcloud beta secrets versions access latest --secret=DOTENV_API > .env
  - id: rails-test
    name: docker/compose:alpine-1.25.4
    entrypoint: sh
    args:
      - -c
      - |
        docker-compose up -d redis db
        sleep 20
        docker-compose run api bundle exec rails db:setup
        docker-compose run api bundle exec rails test -b -v
timeout: 1200s
