steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud kms decrypt --ciphertext-file=.env.production.enc --plaintext-file=.env --location=global --keyring=qoodish --key=qoodish
      gcloud kms decrypt --ciphertext-file=firebase-credentials.prod.json.enc --plaintext-file=firebase-credentials.json --location=global --keyring=qoodish --key=qoodish
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-api:$COMMIT_SHA',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-api:latest',
    '.'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-nginx:$COMMIT_SHA',
    '-t',
    'gcr.io/$PROJECT_ID/$REPO_NAME-nginx:latest',
    '.'
  ]
  dir: 'nginx'
images:
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-api:latest'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-nginx:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/$REPO_NAME-nginx:latest'
