version: '3'
services:
  redis:
    image: redis
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
    command: [
      '--skip-character-set-client-handshake',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_general_ci'
    ]
    ports:
      - '3306'
  api:
    build: .
    volumes:
      - .:/qoodish
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - RAILS_LOG_LEVEL=debug
    command: >
      /bin/bash -c "rm -f /qoodish/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - db
  subscriber:
    build: .
    volumes:
      - .:/qoodish
    env_file: .env
    environment:
      - REDIS_HOST=redis
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - RAILS_LOG_LEVEL=info
    command: >
      bundle exec rails subscriber:run --trace
    depends_on:
      - db
