version: '3'
services:
  redis:
    image: redis
  api:
    build: .
    command: bundle exec rails s -p 4000 -b '0.0.0.0'
    volumes:
      - .:/qoodish
    environment:
      - REDIS_HOST=redis
    ports:
      - '4000:4000'
    depends_on:
      - redis
