json.id place.id
json.place_id place.place_id_val
json.name place.name
json.lat place.lat
json.lng place.lng
json.formatted_address place.formatted_address
json.url place.url
json.opening_hours place.opening_hours
json.thumbnail_url place.thumbnail_url
json.thumbnail_url_400 place.thumbnail_url('400x400')
json.thumbnail_url_800 place.thumbnail_url('800x800')
json.reviews_count place.reviews.size
