json.id map.id
json.author do
  json.id map.user.id
  json.name map.user.name
  json.image map.user.image_variants
  json.image_url map.user.image_url
end
json.name map.name
json.description map.description
json.latitude map.lat
json.longitude map.lng
json.bookmarking false
json.editable false
json.bookmarkable false
json.private map.private
json.image map.image_variants
json.image_url map.image_url
json.created_at map.created_at
json.updated_at map.updated_at
