services:
  app:
    image: ghcr.io/rails/devcontainer/images/ruby:3.3.0
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mysql
  mysql:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_HOST: "%"
    command:
      - --skip-character-set-client-handshake
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
volumes:
  mysql-data:
