name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "283.0.0"
          service_account_email: ${{ secrets.GCP_SA_EMAIL_CI }}
          service_account_key: ${{ secrets.GCP_SA_KEY_CI }}
          export_default_credentials: true
      - id: secrets
        uses: GoogleCloudPlatform/github-actions/get-secretmanager-secrets@master
        with:
          secrets: |-
            RAILS_MASTER_KEY:my-project2-1132/RAILS_MASTER_KEY
            GOOGLE_API_KEY_SERVER:my-project2-1132/GOOGLE_API_KEY_SERVER
            FCM_SERVER_KEY:my-project2-1132/FCM_SERVER_KEY
            GOOGLE_CLIENT_ID:my-project2-1132/GOOGLE_CLIENT_ID
            GOOGLE_CLIENT_EMAIL:my-project2-1132/GOOGLE_CLIENT_EMAIL
            GOOGLE_PRIVATE_KEY:my-project2-1132/GOOGLE_PRIVATE_KEY
      - name: Rails test
        env:
          RAILS_MASTER_KEY: ${{steps.secrets.outputs.RAILS_MASTER_KEY}}
          GOOGLE_API_KEY_SERVER: ${{steps.secrets.outputs.GOOGLE_API_KEY_SERVER}}
          FCM_SERVER_KEY: ${{steps.secrets.outputs.FCM_SERVER_KEY}}
          GOOGLE_CLIENT_ID: ${{steps.secrets.outputs.GOOGLE_CLIENT_ID}}
          GOOGLE_CLIENT_EMAIL: ${{steps.secrets.outputs.GOOGLE_CLIENT_EMAIL}}
          GOOGLE_PRIVATE_KEY: ${{steps.secrets.outputs.GOOGLE_PRIVATE_KEY}}
        run: |
          docker-compose up -d redis db
          sleep 20
          docker-compose run api bundle exec rails db:setup
          docker-compose run api bundle exec rails test -b -v
