name: Dev
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
env:
  PROJECT_ID: qoodish-dev
  REGION: asia-northeast1
  ARTIFACT_REGISTRY: asia-northeast1-docker.pkg.dev
  SERVICE_NAME: qoodish-api
  JOB_NAME: qoodish-runner
  BRANCH_NAME: ${{ github.head_ref }}

jobs:
  test:
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Decrypt secrets
        run: |
          gcloud secrets versions access latest \
            --secret=QOODISH_API_DOTENV \
            --project=$PROJECT_ID \
            --out-file=.env
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Rails test
        env:
          DB_USER: root
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
        run: |
          bundle exec rails db:setup
          bundle exec rails test

  build-and-push-image:
    needs: test
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Decrypt secrets
        run: |
          gcloud secrets versions access latest \
            --secret=QOODISH_API_DOTENV \
            --project=$PROJECT_ID \
            --out-file=.env
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ARTIFACT_REGISTRY }}
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          tags: |
            type=ref,event=pr,prefix=pr-,suffix=
            type=sha,prefix=,suffix=,format=long
      - name: Build and push image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy-runner:
    needs:
      - build-and-push-image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Deploy Job using kustomize
        working-directory: run/dev/runner
        env:
          IMAGE_URL: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        run: |
          echo "Setting image to $IMAGE_URL"
          kustomize edit set image IMAGE_PLACEHOLDER=$IMAGE_URL

          echo "--- Generated job manifest ---"
          kustomize build .
          echo "----------------------------"

          kustomize build . | gcloud beta run jobs replace - \
            --project=$PROJECT_ID \
            --region=$REGION

  deploy-api:
    needs:
      - build-and-push-image
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/438842534630/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: github-actions@qoodish-common.iam.gserviceaccount.com
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
      - name: Normalize branch name for Cloud Run tag
        id: normalize
        run: |
          NORMALIZED_TAG=$(echo "${{ env.BRANCH_NAME }}" | sed 's/[._]/-/g')
          echo "tag=$NORMALIZED_TAG" >> $GITHUB_OUTPUT
          echo "Normalized tag: $NORMALIZED_TAG"
      - name: Deploy Service using kustomize
        working-directory: run/dev/api
        env:
          IMAGE_URL: ${{ env.ARTIFACT_REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        run: |
          echo "Setting image to $IMAGE_URL"
          kustomize edit set image IMAGE_PLACEHOLDER=$IMAGE_URL

          echo "--- Generated service manifest ---"
          kustomize build .
          echo "----------------------------------"

          kustomize build . | gcloud beta run services replace - \
            --project=$PROJECT_ID \
            --region=$REGION
      - name: Update traffic tag to the new revision
        env:
          CLOUDSDK_CORE_DISABLE_PROMPTS: 1
        run: |
          gcloud beta run services update-traffic ${{ env.SERVICE_NAME }} \
            --update-tags=${{ steps.normalize.outputs.tag }}=LATEST \
            --project=$PROJECT_ID \
            --region=$REGION
